// Mirrors src/lib/config/weaponConfigSchema.ts + characterConfigSchema.ts (keys/defaults)
export const WEAPONS = ["ArmingSword","Axe","BastardSword","Bardiche","BattleAxe","Billhook","Dagger","Estoc","ExecutionerSword","Falchion","Falx","FryingPan","Greatsword","HandAxe","Halberd","Longsword","Mace","Mallet","Maul","MeatCleaver","Messer","Poleaxe","Polehammer","Rapier","Quarterstaff","Scimitar","Shortspear","Shortsword","Sickle","SmithHammer","Spear","WarAxe","Warhammer","Zweihander","EveningStar"].sort();
export const WEAPON_GROUPS = ["General","Strike","AltStrike","Stab","AltStab"];
const B=(k,d)=>({key:k,type:"Bool",def:d}), F=(k,d)=>({key:k,type:"Float",def:d}), V2=(k,x,y)=>({key:k,type:"Vector2D",def:{x,y}}), V3=(k,x,y,z)=>({key:k,type:"Vector",def:{x,y,z}}), FA=(k)=>({key:k,type:"FloatArray",def:[]});
export const ATTACK_OPTIONS = [B("CanCombo",true),B("CanMissCombo",true),B("ForcesRearingFromFront",false),B("NoFlinch",false),B("NoReleaseFlinch",false),B("StopOnHit",false),B("DrainAllStamOnBlock",false),B("RagdollOnBlock",false),B("WillClashWhenParried",false),B("RagdollOnHit",false),B("DismountsHorseRider",false),B("DismountsLadderUser",false),F("FlinchSpeedModifier",1.0),F("FlinchDurationModifier",1.0),F("Windup",0.675),F("ComboWindupIncrease",0.25),F("MissComboExtraWindupIncrease",0.2),F("Release",0.325),F("FeintLockOut",0.3),F("FeintCost",10),F("ChamberFeintCost",5),F("ChamberCost",15),F("MorphCost",7),F("HitEffectSpeedUpExponent",3.0),F("StaminaDrain",19.0),F("ExtraStaminaDrainVsHeldBlock",0.0),F("StaminaDamage",0.0),F("WoodDamage",10.0),F("StoneDamage",8.0),F("ChipDamagePercentageOnBlock",0.0),F("MissStaminaCost",10.0),F("HitStaminaReward",10.0),F("MissRecovery",0.7),F("HitKnockbackFactor",1.25),V2("Turncap",150,150),FA("Damage"),FA("HeadBonus"),FA("LegBonus")];
export const GENERAL_OPTIONS = [B("CanBlock",true),B("CanBlockOnFoot",true),B("IsParryHeld",false),B("UsesExtraEnvironmentTracers",true),B("HitKnockbackOnTeammates",false),F("SlideRadius",70.0),F("AttackMask",1),F("ParryMask",5),F("ParryWindowOffset",0.0),F("ParryBackpedalSpeedFactor",1.25),F("ParryHeldStaminaDrain",0.0),F("BoostCosmeticTracersBy",25.0),F("BlockStaminaNegation",13.0),F("SecondBlockStaminaNegation",13.0),V2("ParryTurnCap",375,262.5),V2("ShieldWallTurnCap",80,80),V2("ParrySuccessTurnCap",-1,-1),V2("BlockStaminaClamp",4,20),V2("SecondBlockStaminaClamp",4,20),V3("ClashNormal",0,-1,0),V3("SecondClashNormal",0,-1,0),V3("LastObservedTraceDirection",0,0,0),V3("ParryBoxTransformLocation",0,0,0),V3("ParryBoxTransformRotation",0,0,0),V3("ParryBoxTransformScale",1,1,1)];
export const CHAR_GROUPS = ["Movement","Combat","General","Chftp","Chamber","Parry","Combo","Damage","Stun","Misc"];
export const CHAR_OPTIONS = {
  Movement:[B("CanDodge",false),F("TimeToMaxSprint",0.5),F("CrouchCooldown",0.5),F("SprintingMoveBlockedByFraction",0.2),F("MoveBlockedBySlowMinInterval",0.1),F("FallingTimeToRagdoll",1.5),F("DodgeDuration",0.5),F("DodgeCooldown",1.0),F("DodgeStaminaCost",15)],
  Combat:[B("IsUnflinchable",false),B("IsHitStopOnTeamHitsDisabled",false),B("DisableProjectileRangedDrawFlinch",false),B("CanReceiveClientsideHits",true),B("DisableRagdollFalling",false),B("CannotRequestSuicide",false),B("WillStopMelee",false),B("DisableHealingItems",false),B("IgnoreGameStateHealthRegenRestriction",false),B("IsAllowedOutOfBounds",false),B("TeamkillsCountForAutoKick",true),B("HasLastChance",false),B("ForceRagdollIfDmgAgent",false),B("CanJumpKick",true),F("StructureDamageModifier",1.0),F("StructureRepairModifier",1.0),F("ExtraStaminaOnHit",0),F("StaminaCostModifier",1.0),F("MeleeWindupModifier",1.0),F("MeleeComboExtraWindupModifier",1.0),F("MeleeReleaseModifier",1.0),F("MeleeMissRecoveryModifier",1.0),F("UnflinchableDamageThreshold",0),F("StaminaRegenPerTick",1.5),F("StaminaRegenDelay",1.0),F("StaminaOnKill",30),F("HealthOnKill",0),F("JumpStaminaCost",5),F("HealthRegenDelay",8),F("HealthRegenPerTick",2),F("ReceivedDamageModifier",1.0),F("ReceivedTeamDamageModifier",1.0),F("ReceivedFallDamageModifier",1.0),V3("LowBlockColliderRelativeOffsetLocation",0,0,0),V3("HighBlockColliderRelativeOffsetLocation",0,0,0)],
  General:[B("CannotChamber",false),B("AllowDrop",true),B("AllowClimbing",true),B("AllowVehicles",true),B("AllowEquipmentRotate",true),F("JumpCooldown",0.5),F("LookUpLimit",89),F("LookDownLimit",-89),F("LookUpRateCap",0)],
  Chftp:[{...B("ChftpStun",false),toggle:true},{...F("ChftpStunDuration",1.0),gatedBy:"ChftpStun"},{...F("ChftpStunMovementRestriction",0.5),gatedBy:"ChftpStun"},{...B("ChftpStunDisarms",false),gatedBy:"ChftpStun"},{key:"ChftpStunAnimation",type:"String",def:"Default",choices:["Default","Stagger","Knockdown"],gatedBy:"ChftpStun"},{...V2("ChftpStunTurnCap",60,60),gatedBy:"ChftpStun"},{...F("ChftpStunStaminaCost",10),gatedBy:"ChftpStun"},{...F("ChftpStunAttackerStaminaReward",10),gatedBy:"ChftpStun"},{...B("ChftpStunExcludeStabs",false),gatedBy:"ChftpStun"},{...B("ChftpStunIgnoreEarlyRelease",false),gatedBy:"ChftpStun"},{...B("ChftpStunCanParry",true),gatedBy:"ChftpStun"},{...F("ChftpStunParryDuration",0.3),gatedBy:"ChftpStun"},{...F("ChftpStunParryRecoveryTime",0.5),gatedBy:"ChftpStun"}],
  Chamber:[{...B("ChamberSlowdown",false),toggle:true},{...F("ChamberSlowdownDuration",0.5),gatedBy:"ChamberSlowdown"}],
  Parry:[{...B("ExperimentalParry",false),toggle:true},{...F("ExperimentalParryDuration",0.4),gatedBy:"ExperimentalParry"},{...B("KicksUnparryable",false),toggle:true},{...B("TrueCombo",false),toggle:true},{...F("TrueComboRecoveryTime",0.3),gatedBy:"TrueCombo"},{...F("TrueComboStamina",5),gatedBy:"TrueCombo"}],
  Combo:[],
  Damage:[{...B("TeamDamageReflect",false),toggle:true},{...F("TeamDamageReflectPercent",50),gatedBy:"TeamDamageReflect"},{...B("TeamHitRecovery",false),toggle:true},{...F("TeamHitRecoveryExtraTime",0.2),gatedBy:"TeamHitRecovery"}],
  Stun:[],
  Misc:[{...B("DisarmPickupDelay",false),toggle:true},{...F("DisarmPickupDelayDuration",2.0),gatedBy:"DisarmPickupDelay"},{...B("DelayedSuicide",false),toggle:true},{...F("DelayedSuicideDuration",3.0),gatedBy:"DelayedSuicide"}]
};
// Sample overrides: weapons/{weapon}/{group}/{key} -> value ; character/{group}/{key}
export const SAMPLE_OVERRIDES = {
  weapons: {
    Greatsword:{Strike:{Windup:0.6,Release:0.35,CanCombo:true},Stab:{Windup:0.7},General:{ParryTurnCap:{x:400,y:280}}},
    Longsword:{Strike:{Windup:0.625},AltStrike:{StaminaDrain:17}},
    Maul:{Strike:{HitKnockbackFactor:1.6,RagdollOnHit:true},General:{SlideRadius:80}},
    Rapier:{Stab:{Windup:0.55,Release:0.3,FeintCost:8}},
    Zweihander:{Strike:{Windup:0.7},AltStrike:{Windup:0.7},Stab:{Windup:0.75}},
    Dagger:{General:{CanBlock:false}},
    Spear:{Stab:{Turncap:{x:120,y:120}}},
  },
  character: { Movement:{CanDodge:true,DodgeCooldown:0.8,DodgeStaminaCost:12}, Chftp:{ChftpStun:true,ChftpStunDuration:1.2}, Combat:{StaminaRegenDelay:1.2} }
};
export const PRESETS = {
  user:[{name:"comp-duels",title:"Comp Duels",description:"Tighter windups, cheaper feints. Tuned with the NA duel league."},{name:"slow-mo",title:"Slow Mo Sundays",description:"Everything 30% slower. Party mode."}],
  builtin:[{name:"vanilla",title:"Vanilla",description:"Stock Mordhau values. Clears every override."},{name:"classic-2020",title:"Classic 2020",description:"Pre-patch-22 combat timings."},{name:"feint-heavy",title:"Feint Heavy",description:"Reduced feint and morph costs across all weapons."}]
};
export const USERS=[{username:"amori",role:"admin"},{username:"kestrel",role:"config_editor"},{username:"bram",role:"config_editor"}];
export const NOTES={Windup:[{id:"1",by:"kestrel",text:"Dropped from 0.675 after league feedback — chambers felt too easy."},{id:"2",by:"amori",text:"Re-check after next mod build; ties into TrueCombo timing."}],CanDodge:[{id:"3",by:"amori",text:"Enabled for the party server only. Keep off in comp presets."}]};
export function fmt(v){ if(v===null||v===undefined) return "Game Default"; if(typeof v==="boolean") return v?"true":"false"; if(typeof v==="number") return String(v); if(Array.isArray(v)) return "["+v.join(", ")+"]"; if("z" in v) return `{x: ${v.x}, y: ${v.y}, z: ${v.z}}`; return `{x: ${v.x}, y: ${v.y}}`; }
export function buildCommands(){ const out=[]; for(const [w,gs] of Object.entries(SAMPLE_OVERRIDES.weapons)) for(const [g,ks] of Object.entries(gs)) for(const [k,v] of Object.entries(ks)) out.push(`Weapon ${w} ${g} ${k} ${fmtCmd(v)}`); for(const [g,ks] of Object.entries(SAMPLE_OVERRIDES.character)) for(const [k,v] of Object.entries(ks)) out.push(`Character ${g} ${k} ${fmtCmd(v)}`); return out.sort((a,b)=>a.toLowerCase().localeCompare(b.toLowerCase())); }
function fmtCmd(v){ if(typeof v==="object"&&!Array.isArray(v)) return Object.values(v).join(","); return fmt(v); }
