import { DataType, type ConfigEntry } from "./types";

const lifecycle =
  " Takes effect on the next attack.";

const cswicsReferences: Record<string, string> = {
  StrikeChamberWindow: "customStrikeChamberWindow",
  StabChamberWindow: "customStabChamberWindow",
  StrikeFeintWindow: "StrikeFeintWindow",
  StabFeintWindow: "StabFeintWindow",
  StrikeMorphWindow: "customStrikeMorphWIndow. It used 1 minus the input, replaced zero with 0.0001, and also adjusted the morph-time limit; copying its input directly is not equivalent",
  StabMorphWindow: "customStabMorphWIndow. It used 1 minus the input, replaced zero with 0.0001, and also adjusted the morph-time limit; copying its input directly is not equivalent",
  StrikeMaxMorphTotalTime: "StrikeMorphLimit",
  StabMaxMorphTotalTime: "StabMorphLimit",
  OneHandedStrikeMinWindUpTimeBeforeMorphing: "MinTimeStrikeStabMorphs.X. Its original list did not include mounted attacks",
  TwoHandedStrikeMinWindUpTimeBeforeMorphing: "MinTimeStrikeStabMorphs.Y",
  PolearmStrikeMinWindUpTimeBeforeMorphing: "MinTimeStrikeStabMorphs.Z",
  AttackActiveParryWindow: "ActiveParryDuration",
  AttackClashAngle: "customClashAngle",
  AttackTraceMemoryStayDuration: "customTracerHangTime",
  StrikeGlanceMinimumTurnAmount: "customGlanceTurnAmount.X, which also set the blocked-strike threshold",
  StrikeGlanceBlockedMinimumTurnAmount: "customGlanceTurnAmount.X, which also set the normal-strike threshold",
  StrikeGlanceOppositeMinimumTurnAmount: "customGlanceTurnAmount.Y, which also set the blocked opposite-direction threshold",
  StrikeGlanceBlockedOppositeMinimumTurnAmount: "customGlanceTurnAmount.Y, which also set the normal opposite-direction threshold",
  DisableStrikeEndReleaseGlances: "disableEndReleaseGlances",
  StrikeExtraEarlyReleaseForLookUpOverheads: "CustomExtraEarlyRelease.X",
  StrikeExtraEarlyReleaseForLookUpNonUndercuts: "CustomExtraEarlyRelease.Y",
  StrikeCounterCompensateWeight: "customCompensationOne.X",
  StrikeCounterCompensateLookTime: "customCompensationOne.Y",
  StrikeMaxTurnCompensation: "customCompensationOne.Z",
  StrikeCounterCompensateOverheadFixupTerm: "customCompensationTwo.X",
  StrikeCounterCompensateOverheadFixupTiltTerm: "customCompensationTwo.Y",
  StrikeEarlyRelease: "ConfigStrikeEarlyRelease.A",
  StrikeEarlyReleaseTimeFactor: "ConfigStrikeEarlyRelease.B",
  StrikeRiposteEarlyRelease: "ConfigStrikeEarlyRelease.C",
  StrikeRiposteEarlyReleaseTimeFactor: "ConfigStrikeEarlyRelease.D",
  StabEarlyRelease: "ConfigStabEarlyRelease.A",
  StabEarlyReleaseTimeFactor: "ConfigStabEarlyRelease.B",
  StabRiposteEarlyRelease: "ConfigStabEarlyRelease.C",
  StabRiposteEarlyReleaseTimeFactor: "ConfigStabEarlyRelease.D",
};

function scalar(configKey: string, documentation: string, measured = false): ConfigEntry {
  return {
    configKey,
    dataType: DataType.Float,
    isImplemented: measured,
    defaultVariesByMotion: true,
    documentation: documentation + lifecycle,
  };
}

export const ATTACK_MOTION_CONFIG_OPTIONS: ConfigEntry[] = [
  scalar("StrikeChamberWindow", "Controls the timing window for chambering an incoming attack with a strike. The exact cutoff and how it changes with this value still need testing."),
  scalar("StabChamberWindow", "Controls the timing window for chambering an incoming attack with a stab. The exact cutoff and how it changes with this value still need testing."),
  scalar("StrikeFeintWindow", "Controls how early feinting is cut off before a strike releases. Higher values stop you feinting earlier; lower values allow later feints. Does not change combo feint timing. MissComboPenalty takes priority on a missed combo.", true),
  scalar("StabFeintWindow", "Controls the cutoff for feinting a stab before it releases. Higher values are expected to close the opportunity earlier, as they do for strikes. Does not change combo feint timing. MissComboPenalty takes priority on a missed combo."),
  scalar("StrikeMorphWindow", "Controls the cutoff for changing a strike into a stab. Higher values close the opportunity earlier; small positive values allow later morphs. StrikeMaxMorphTotalTime can still prevent a morph. This value is not the duration of the allowed morph window.", true),
  scalar("StabMorphWindow", "Controls the cutoff for changing a stab into a strike. Higher values are expected to close the opportunity earlier, as they do for strikes. StabMaxMorphTotalTime can still prevent a morph."),
  scalar("StrikeMaxMorphTotalTime", "An additional time limit on changing a strike into a stab. Increasing it can allow morphs that a lower limit rejects. StrikeMorphWindow still controls when the opportunity closes. The exact start and end points of this timer still need testing.", true),
  scalar("StabMaxMorphTotalTime", "An additional time limit on changing a stab into a strike. StabMorphWindow still controls when the opportunity closes. The exact start and end points of this timer still need testing."),
  scalar("OneHandedStrikeMinWindUpTimeBeforeMorphing", "Minimum wait after starting a one-handed strike before it can change into a stab. Earlier morph inputs wait until this delay has passed. Higher values delay the change longer. Also covers shield, ladder and mounted one-handed attacks."),
  scalar("TwoHandedStrikeMinWindUpTimeBeforeMorphing", "Minimum wait after starting a two-handed sword strike before it can change into a stab. Earlier morph inputs wait until this delay has passed. Higher values delay the change longer. Covers the two-handed sword and greatsword attack animations."),
  scalar("PolearmStrikeMinWindUpTimeBeforeMorphing", "Minimum wait after starting a polearm strike before it can change into a stab. Earlier morph inputs wait until this delay has passed. Higher values delay the change longer. Covers regular and long polearm attack animations."),
  scalar("AttackActiveParryWindow", "Controls the active-parry timing during a strike or stab. This does not set the duration of your normal parry. The exact timing and effect of increasing this value still need testing."),
  scalar("AttackClashAngle", "Controls the angle check used when attacks clash with each other. The exact angle being compared, and whether a larger value makes clashes easier, still need testing."),
  scalar("AttackTraceMemoryStayDuration", "How long the game remembers an attack's final hit-detection trace for fast parry-recovery checks. Higher values keep that trace around longer."),
  scalar("StrikeGlanceMinimumTurnAmount", "Turn threshold used to decide whether a normal strike becomes a glancing hit. How much turning this permits, and how increasing the value changes glancing, still need testing."),
  scalar("StrikeGlanceBlockedMinimumTurnAmount", "Turn threshold used for glancing in the blocked-strike case. Its exact relationship to the normal strike threshold still needs testing."),
  scalar("StrikeGlanceOppositeMinimumTurnAmount", "Glance threshold for turning in the opposite direction during a strike. How increasing the value changes glancing still needs testing."),
  scalar("StrikeGlanceBlockedOppositeMinimumTurnAmount", "Glance threshold for opposite-direction turning in the blocked-strike case. Its exact effect still needs testing."),
  {
    configKey: "DisableStrikeEndReleaseGlances",
    dataType: DataType.Bool,
    isImplemented: false,
    default: false,
    documentation: "Intended to prevent a strike from becoming a glancing hit just because it lands near the end of its release. Does not disable the separate turn-based glance checks. Off keeps normal behavior. Gameplay effect not yet confirmed." + lifecycle,
  },
  scalar("StrikeExtraEarlyReleaseForLookUpOverheads", "Adjusts the extra early-release allowance when looking up during an overhead strike. The units and how this changes hit timing still need testing."),
  scalar("StrikeExtraEarlyReleaseForLookUpNonUndercuts", "Adjusts the extra early-release allowance when looking up during strikes other than undercuts. The units and how this changes hit timing still need testing."),
  scalar("StrikeCounterCompensateWeight", "Adjusts the strength of a strike's turn compensation. The amount and direction of the change are not yet understood well enough to recommend higher or lower values."),
  scalar("StrikeCounterCompensateLookTime", "Adjusts the look-timing component of strike turn compensation. What period this measures and how it affects the swing still need testing."),
  scalar("StrikeMaxTurnCompensation", "Sets a limit on a strike's turn compensation. How that limit changes the swing is not yet confirmed; it is separate from the weapon's turn-speed cap."),
  scalar("StrikeCounterCompensateOverheadFixupTerm", "Adjusts turn compensation specifically for overhead strikes. Normal values can be negative. The effect of raising or lowering this value is not yet understood."),
  scalar("StrikeCounterCompensateOverheadFixupTiltTerm", "Adjusts the tilt correction used in overhead-strike turn compensation. The effect of raising or lowering this value is not yet understood."),
  scalar("StrikeEarlyRelease", "Fraction of a strike's release treated as early release. For example, 0.25 represents 25% of the release, not 250 milliseconds. Higher values assign a larger portion to early release; the effect on hit timing still needs testing."),
  scalar("StrikeEarlyReleaseTimeFactor", "Adjusts timing during the early-release portion of a strike. Whether higher values speed up or slow down that portion still needs testing."),
  scalar("StrikeRiposteEarlyRelease", "Early-release fraction for a strike performed as a riposte after a successful parry. For example, 0.25 represents 25% of its release. The effect on hit timing still needs testing."),
  scalar("StrikeRiposteEarlyReleaseTimeFactor", "Adjusts early-release timing for a riposte strike. Whether higher values speed up or slow down that portion still needs testing."),
  scalar("StabEarlyRelease", "Fraction of a stab's release treated as early release. For example, 0.25 represents 25% of the release, not 250 milliseconds. The effect on hit timing still needs testing."),
  scalar("StabEarlyReleaseTimeFactor", "Adjusts timing during the early-release portion of a stab. Whether higher values speed up or slow down that portion still needs testing."),
  scalar("StabRiposteEarlyRelease", "Early-release fraction for a stab performed as a riposte after a successful parry. For example, 0.25 represents 25% of its release. The effect on hit timing still needs testing."),
  scalar("StabRiposteEarlyReleaseTimeFactor", "Adjusts early-release timing for a riposte stab. Whether higher values speed up or slow down that portion still needs testing."),
].map(entry => ({
  ...entry,
  documentation: `${entry.documentation} Cswics mod: ${cswicsReferences[entry.configKey]}.`,
}));
