import { DataType } from "./types";

export enum CharacterConfigGroupName {
  Movement = "Movement",
  Combat = "Combat",
  General = "General",
}

export const CHARACTER_CONFIG_OPTIONS = {
  Movement: [
    // Booleans
    {
      configKey: "CanDodge",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },

    // Floats
    {
      configKey: "CrouchCooldown",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.15,
    },
    {
      configKey: "SprintingMoveBlockedByFraction",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.1,
    },
    {
      configKey: "MoveBlockedBySlowMinInterval",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.5,
    },
    {
      configKey: "FallingTimeToRagdoll",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.5,
    },
    {
      configKey: "DodgeDuration",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.375,
    },
    {
      configKey: "DodgeCooldown",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.15,
    },
    {
      configKey: "DodgeStaminaCost",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 10,
    },
  ],

  Combat: [
    // Booleans
    {
      configKey: "IsUnflinchable",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "IsHitStopOnTeamHitsDisabled",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "DisableProjectileRangedDrawFlinch",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "CanReceiveClientsideHits",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "DisableRagdollFalling",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "CannotRequestSuicide",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "WillStopMelee",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "DisableHealingItems",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "IgnoreGameStateHealthRegenRestriction",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "IsAllowedOutOfBounds",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "TeamkillsCountForAutoKick",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: true,
    },
    {
      configKey: "HasLastChance",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "ForceRagdollIfDmgAgent",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "CanJumpKick",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: true,
    },
    {
      configKey: "AlwaysStunInsteadOfDisarm",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },

    // Floats
    {
      configKey: "StructureDamageModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "StructureRepairModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "ExtraStaminaOnHit",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0,
    },
    {
      configKey: "StaminaCostModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "MeleeWindupModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "MeleeComboExtraWindupModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "MeleeReleaseModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "MeleeMissRecoveryModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "LegDamageBonusModifierAirborne",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "UnflinchableDamageThreshold",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.0,
    },
    {
      configKey: "StaminaRegenPerTick",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 6,
    },
    {
      configKey: "StaminaRegenDelay",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.3,
    },
    {
      configKey: "StaminaOnKill",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 25,
    },
    {
      configKey: "HealthOnKill",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 25,
    },
    {
      configKey: "StaminaRegenTickRate",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.25,
    },
    {
      configKey: "JumpStaminaCost",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 10.0,
    },
    {
      configKey: "KnockbackParry",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 450.0,
    },
    {
      configKey: "KnockbackWorld",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 400.0,
    },
    {
      configKey: "KnockbackClash",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 400.0,
    },
    {
      configKey: "DamageArmorTierOverride",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: -1,
    },
    {
      configKey: "HealthRegenDelay",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 4.5,
    },
    {
      configKey: "HealthRegenPerTick",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 5,
    },
    {
      configKey: "HealthRegenTickRate",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.25,
    },
    {
      configKey: "OutOfBoundsKillTime",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 5.0,
    },
    {
      configKey: "ReflectMeleeDamagePercentage",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.0,
    },
    {
      configKey: "LastChanceHealAmount",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0,
    },
    {
      configKey: "ReceivedDamageModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "ReceivedFallDamageModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "ReceivedTeamDamageModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "ReceivedFireDamageModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "ReceivedRangedDamageModifier",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },
    {
      configKey: "ReceivedDamageAbsorption",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.0,
    },
    {
      configKey: "ReceivedDamageMax",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.0,
    },
    {
      configKey: "KnockbackFlinch",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 325.0,
    },
    {
      configKey: "RagdollForceMultIfDmgAgent",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 1.0,
    },

    // Vectors - Low Block Collider Relative Offset
    {
      configKey: "LowBlockColliderRelativeOffsetLocation",
      dataType: DataType.Vector,
      isImplemented: false,
      documentation: "",
      default: { x: 75.0, y: 0.0, z: -35.0 },
    },
    {
      configKey: "LowBlockColliderRelativeOffsetRotation",
      dataType: DataType.Vector,
      isImplemented: false,
      documentation: "",
      default: { x: 0.0, y: 59.999985, z: 0.0 },
    },
    {
      configKey: "LowBlockColliderRelativeOffsetScale",
      dataType: DataType.Vector,
      isImplemented: false,
      documentation: "",
      default: { x: 1.0, y: 1.0, z: 0.81 },
    },

    // Vectors - High Block Collider Relative Offset
    {
      configKey: "HighBlockColliderRelativeOffsetLocation",
      dataType: DataType.Vector,
      isImplemented: false,
      documentation: "",
      default: { x: 10.0, y: 0.0, z: -100.0 },
    },
    {
      configKey: "HighBlockColliderRelativeOffsetRotation",
      dataType: DataType.Vector,
      isImplemented: false,
      documentation: "",
      default: { x: 0.0, y: -44.999989, z: 0.0 },
    },
    {
      configKey: "HighBlockColliderRelativeOffsetScale",
      dataType: DataType.Vector,
      isImplemented: false,
      documentation: "",
      default: { x: 1.0, y: 1.0, z: 1.1 },
    },
  ],

  General: [
    // Booleans
    {
      configKey: "CannotChamber",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: false,
    },
    {
      configKey: "AllowDrop",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: true,
    },
    {
      configKey: "AllowClimbing",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: true,
    },
    {
      configKey: "AllowVehicles",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: true,
    },
    {
      configKey: "AllowEquipmentRotate",
      dataType: DataType.Boolean,
      isImplemented: false,
      documentation: "",
      default: true,
    },

    // Floats
    {
      configKey: "JumpCooldown",
      dataType: DataType.Float,
      isImplemented: false,
      documentation: "",
      default: 0.15,
    },
  ],
};
export const characterConfigFlatMap = Object.values(CHARACTER_CONFIG_OPTIONS)
  .reduce((acc, group) => [...acc, ...group], [])
  .reduce(
    (acc, configEntry) => ({
      ...acc,
      [configEntry.configKey]: configEntry,
    }),
    {},
  );

export type CharacterConfigKeyType = keyof typeof characterConfigFlatMap;
