import { DataType, type ConfigEntry } from "./types";

export const MOVEMENT_CONFIG_OPTIONS: ConfigEntry[] = [
  {
    configKey: "MaxWalkSpeed",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Sets the underlying walking speed in Unreal units per second; native sprint also builds on this value. Armor, perks, equipment, direction and movement restrictions can affect the resulting speed. Updates and Reset affect ongoing movement as configuration arrives, while native acceleration and braking govern velocity. A large increase can make native sprint acceleration restart. In tested grounded walking, zero and negative values stop movement rather than reverse it. Cswics mod: customMovementSpeedMultiplier.X × 308.",
  },
  {
    configKey: "MaxWalkSpeedCrouched",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Sets underlying crouching speed in Unreal units per second for characters without the Rat perk. Rat crouching has its own independent control. Armor, equipment and movement restrictions still affect the result. Updates and Reset affect ongoing movement as configuration arrives, with native acceleration and braking retained. In tested grounded crouching, zero and negative values stop movement rather than reverse it. Cswics mod: customMovementSpeedMultiplier.X × 270.",
  },
  {
    configKey: "MaxWalkSpeedCrouchedWithRatPerk",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Sets underlying crouching speed in Unreal units per second for characters with the Rat perk. This does not grant the perk or change ordinary crouching. Armor, equipment and movement restrictions still affect the result. Updates and Reset affect ongoing movement as configuration arrives and remain effective after profile rebuilds. In tested grounded Rat crouching, zero and negative values stop movement rather than reverse it. Cswics mod: customMovementSpeedMultiplier.X × 296.",
  },
  {
    configKey: "BackpedalModifier",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Scales native backward movement speed. In tested walking, doubling a positive modifier doubled backward speed; armor, equipment and movement restrictions still affect the result. Updates and Reset affect ongoing movement as configuration arrives. Zero and negative values produced alternating stops and movement in the test fixture, not reverse movement or a reliable stop. Cswics mod: StrafeAndBackpedal.X.",
  },
  {
    configKey: "StrafeModifier",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Scales native sideways movement speed. In tested walking, doubling a positive modifier doubled sideways speed; armor, equipment and movement restrictions still affect the result. Updates and Reset affect ongoing movement as configuration arrives. Zero and negative values produced alternating stops and movement in the test fixture, not reverse movement or a reliable stop. Cswics mod: StrafeAndBackpedal.Y.",
  },
  {
    configKey: "PartialSprintModifier",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Scales native partial-sprint speed, including movement while ChamberSlowdown imposes its partial-sprint restriction. Changing this value does not cancel or extend that restriction. Walking speed, armor and native movement rules still affect the result. Updates and Reset affect ongoing movement; native sprint eligibility can recalculate. Cswics mod: customMovementSpeedMultiplier.Y.",
  },
  {
    configKey: "SprintModifier",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Scales the full-sprint speed target relative to underlying walking speed. Partial sprint, TimeToMaxSprint, acceleration, armor and native restrictions still affect how that speed is reached. Updates and Reset affect ongoing movement without EZConfig forcing velocity or restarting actions; native sprint eligibility can recalculate. Cswics mod: customMovementSpeedMultiplier.Z.",
  },
  {
    configKey: "SprintAcceleration",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Sets the underlying acceleration during full sprint, in Unreal units per second squared. Loadout can scale it. TimeToMaxSprint separately ramps the allowed speed target, so increasing acceleration alone need not make that target rise faster. Updates and Reset affect ongoing movement through native processing. Cswics mod: customMovementAccelerations.X × 200.",
  },
  {
    configKey: "SupersprintModifier",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Scales native supersprint speed, including the lunge within an attack's existing supersprint window. This changes speed rather than the window's duration; supersprint has its own native acceleration and speed calculation. Updates and Reset affect ongoing native movement. Cswics mod: customMovementAccelerations.Y.",
  },
  {
    configKey: "AttackSupersprintDuration",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Sets the supersprint movement window in seconds for an applicable new main-mode attack, independently of alternate mode. The mode belongs to the weapon performing the attack. Fist attacks and kicks are included; kicks use their own attack mode, not the held weapon's grip. Couched attacks are excluded. Each attack captures its value; later configuration updates and wipes preserve that attack's captured window. Native attack phase, start offset and movement eligibility still determine when the window runs. This does not set the whole attack's duration or its supersprint speed. When no override is present, the native weapon or range-curve default applies. Reset removes the saved override for the next wipe-and-apply. Cswics assigned the same value to both modes; these controls are independent. Cswics mod: customMovementAccelerations.Z.",
  },
  {
    configKey: "SecondAttackSupersprintDuration",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Sets the supersprint movement window in seconds for an applicable new alternate-mode attack, independently of main mode. The mode belongs to the weapon performing the attack. Fist attacks and kicks are included; kicks use their own attack mode, not the held weapon's grip. Couched attacks are excluded. Each attack captures its value; later configuration updates and wipes preserve that attack's captured window. Native attack phase, start offset and movement eligibility still determine when the window runs. This does not set the whole attack's duration or its supersprint speed. When no override is present, the native weapon or range-curve default applies. Reset removes the saved override for the next wipe-and-apply. Cswics assigned the same value to both modes; these controls are independent. Cswics mod: customMovementAccelerations.Z.",
  },
  {
    configKey: "SubSprintSpeedBonusEquipped",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Changes the equipment contribution to walking speed in main mode, independently of alternate mode. In tested walking, +0.2 increased speed and -0.2 reduced it; this is a native contribution, not a final-speed multiplier. Native ladder climbing also consumed this contribution: changing +0.12 to zero reduced the measured climb speed without changing ladder geometry or adding a vehicle-speed control. Values follow their mode when grip changes. Applied updates and wipes affect ongoing movement through native recalculation. Reset removes the saved override; the next wipe-and-apply restores removed overrides to each item's own class defaults. Armor, other equipment values and native movement restrictions still affect speed. Setting both subsprint controls to zero reproduces Cswics' paired property writes without removing every equipment movement penalty. Cswics mod: disableWeaponSpecificSlowdown (SubSprintSpeedBonusEquipped = 0).",
  },
  {
    configKey: "SecondSubSprintSpeedBonusEquipped",
    dataType: DataType.Float,
    isImplemented: true,
    requiresExplicitValue: true,
    documentation: "Changes the equipment contribution to walking speed in alternate mode, independently of main mode. Tested positive values increased walking speed; this is a native contribution, not a final-speed multiplier. Values follow their mode when grip changes. Applied updates and wipes affect ongoing movement through native recalculation. Reset removes the saved override; the next wipe-and-apply restores removed overrides to each item's own class defaults. Armor, other equipment values and native movement restrictions still affect speed. Setting both subsprint controls to zero reproduces Cswics' paired property writes without removing every equipment movement penalty. Cswics mod: disableWeaponSpecificSlowdown (SecondSubSprintSpeedBonusEquipped = 0).",
  },
];
